spring:
  application:
    name: contactapi
  datasource:
    url: jdbc:postgresql://localhost:5432/contactflowdb
    username: postgres
    password: Xn68!gqbg
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    async:
      request-timeout: 3600000

---
server:
  port: 8080
#  error:
#    path: /user/error
#    whitelabel:
#      enabled: false
